from app.config.settings import settings

DATABASE_URL = settings.DATABASE_URL
DEBUG = settings.DEBUG
SECRET_KEY = settings.SECRET_KEY
BETTER_AUTH_URL = settings.BETTER_AUTH_URL
API_URL = settings.API_URL
APP_URL = settings.APP_URL
REDIS_URL = settings.REDIS_URL
BLOB_READ_WRITE_TOKEN = settings.BLOB_READ_WRITE_TOKEN
AGENT_BRIDGE_SECRET = settings.AGENT_BRIDGE_SECRET
ALLOWED_SIGN_IN = settings.ALLOWED_SIGN_IN
CRON_SECRET = settings.CRON_SECRET
CONTEXT_DEV_API_KEY = settings.CONTEXT_DEV_API_KEY
PERPLEXITY_API_KEY = settings.PERPLEXITY_API_KEY
AI_GATEWAY_API_KEY = settings.AI_GATEWAY_API_KEY
GOOGLE_CLIENT_ID = settings.GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET = settings.GOOGLE_CLIENT_SECRET
MICROSOFT_CLIENT_ID = settings.MICROSOFT_CLIENT_ID
MICROSOFT_CLIENT_SECRET = settings.MICROSOFT_CLIENT_SECRET
MICROSOFT_TENANT_ID = settings.MICROSOFT_TENANT_ID
