"""agent_run input column

Revision ID: 6a38d7f18f65
Revises: 05d363568d0c
Create Date: 2026-10-06 11:42:31.986401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a38d7f18f65'
down_revision: Union[str, None] = '05d363568d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentRun', sa.Column('input', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agentRun', 'input')
    # ### end Alembic commands ###
